services:
  - type: web
    name: lprs-web
    env: python
    plan: free            # 512 MB RAM, sleeps when idle
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --preload --workers 1 --threads 4 --bind 0.0.0.0:$PORT"
    autoDeploy: true
    envVars:
      - key: MONGO_URI     # fill in dashboard
        sync: false
      - key: MONGO_DB
        value: license_plate_db


